In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\dell\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

In [4]:
df=pd.read_csv("sample_data.csv")
df

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active
0,101,Aarav Sharma,Engineering,85000,28,2021-03-15,Delhi,4.5,True
1,102,Priya Mehta,Marketing,62000,32,2019-07-22,Mumbai,3.8,True
2,103,Rohan Verma,Engineering,92000,35,2018-01-10,Bangalore,4.7,True
3,104,Sneha Iyer,HR,54000,27,2022-05-30,Chennai,4.1,True
4,105,Kunal Joshi,Finance,71000,30,2020-11-18,Pune,3.5,False
5,106,Ananya Singh,Engineering,88000,29,2021-08-05,Hyderabad,4.6,True
6,107,Vikram Nair,Marketing,67000,34,2018-09-14,Delhi,3.9,True
7,108,Divya Patel,Finance,74000,31,2019-04-25,Ahmedabad,4.2,True
8,109,Arjun Kapoor,HR,57000,26,2023-01-12,Mumbai,3.7,False
9,110,Meera Reddy,Engineering,95000,37,2017-06-08,Bangalore,4.9,True
10,111,Siddharth Das,Data Science,105000,33,2020-02-20,Hyderabad,4.8,True
11,112,Nisha Gupta,Marketing,60000,28,2022-10-01,Delhi,3.6,True
12,113,Rahul Bose,Data Science,98000,36,2019-12-17,Pune,4.4,False
13,114,Tanvi Sharma,Engineering,83000,27,2022-03-29,Chennai,4.3,True
14,115,Karan Malhotra,Finance,69000,29,2021-07-11,Mumbai,3.8,True
15,116,Pooja Tiwari,HR,52000,25,2023-06-15,Delhi,4.0,True
16,117,Aditya Kumar,Data Science,110000,38,2016-11-03,Bangalore,4.9,True
17,118,Riya Chopra,Marketing,63000,30,2020-08-19,Hyderabad,3.7,False
18,119,Manish Sinha,Engineering,89000,32,2019-05-07,Pune,4.5,True
19,120,Deepika Rao,Data Science,102000,34,2018-03-22,Mumbai,4.6,True

# use of groupby

In [5]:
avg_df=df.groupby('department')['salary'].mean()

# find duplicates

In [6]:
df_duplicate=df[df.duplicated('city')]
df_duplicate

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active
6,107,Vikram Nair,Marketing,67000,34,2018-09-14,Delhi,3.9,True
8,109,Arjun Kapoor,HR,57000,26,2023-01-12,Mumbai,3.7,False
9,110,Meera Reddy,Engineering,95000,37,2017-06-08,Bangalore,4.9,True
10,111,Siddharth Das,Data Science,105000,33,2020-02-20,Hyderabad,4.8,True
11,112,Nisha Gupta,Marketing,60000,28,2022-10-01,Delhi,3.6,True
12,113,Rahul Bose,Data Science,98000,36,2019-12-17,Pune,4.4,False
13,114,Tanvi Sharma,Engineering,83000,27,2022-03-29,Chennai,4.3,True
14,115,Karan Malhotra,Finance,69000,29,2021-07-11,Mumbai,3.8,True
15,116,Pooja Tiwari,HR,52000,25,2023-06-15,Delhi,4.0,True
16,117,Aditya Kumar,Data Science,110000,38,2016-11-03,Bangalore,4.9,True
17,118,Riya Chopra,Marketing,63000,30,2020-08-19,Hyderabad,3.7,False
18,119,Manish Sinha,Engineering,89000,32,2019-05-07,Pune,4.5,True
19,120,Deepika Rao,Data Science,102000,34,2018-03-22,Mumbai,4.6,True

# drop duplicate

In [7]:
df_duplicate.drop_duplicates(subset='city',inplace=True)

C:\Users\DELL\AppData\Local\Temp\ipykernel_12052\2210637647.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_duplicate.drop_duplicates(subset='city',inplace=True)

# filtering data

In [8]:
df[(df['city']=='Delhi') & (df['age']>28)]

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active
6,107,Vikram Nair,Marketing,67000,34,2018-09-14,Delhi,3.9,True

# handling with missing data

In [9]:
df['city'].fillna(df['city'].mode().iloc[0])

0         Delhi
1        Mumbai
2     Bangalore
3       Chennai
4          Pune
5     Hyderabad
6         Delhi
7     Ahmedabad
8        Mumbai
9     Bangalore
10    Hyderabad
11        Delhi
12         Pune
13      Chennai
14       Mumbai
15        Delhi
16    Bangalore
17    Hyderabad
18         Pune
19       Mumbai
Name: city, dtype: object

# apply function

In [10]:
df['New Salary']=df['salary'].apply(lambda x: x*1.10)

In [11]:
df.head()

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active,New Salary
0,101,Aarav Sharma,Engineering,85000,28,2021-03-15,Delhi,4.5,True,93500.0
1,102,Priya Mehta,Marketing,62000,32,2019-07-22,Mumbai,3.8,True,68200.0
2,103,Rohan Verma,Engineering,92000,35,2018-01-10,Bangalore,4.7,True,101200.0
3,104,Sneha Iyer,HR,54000,27,2022-05-30,Chennai,4.1,True,59400.0
4,105,Kunal Joshi,Finance,71000,30,2020-11-18,Pune,3.5,False,78100.0

# sorting data

In [13]:
df.sort_values(by='name',ascending=True,inplace=True)
df.head()

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active,New Salary
0,101,Aarav Sharma,Engineering,85000,28,2021-03-15,Delhi,4.5,True,93500.0
16,117,Aditya Kumar,Data Science,110000,38,2016-11-03,Bangalore,4.9,True,121000.0
5,106,Ananya Singh,Engineering,88000,29,2021-08-05,Hyderabad,4.6,True,96800.0
8,109,Arjun Kapoor,HR,57000,26,2023-01-12,Mumbai,3.7,False,62700.0
19,120,Deepika Rao,Data Science,102000,34,2018-03-22,Mumbai,4.6,True,112200.0

# Top N Records per Group

In [15]:
df['rank'] = df.groupby('department')['salary'].rank(method='dense', ascending=False)
df[df['rank'] <= 2]

,employee_id,name,department,salary,age,joining_date,city,performance_score,is_active,New Salary,rank
16,117,Aditya Kumar,Data Science,110000,38,2016-11-03,Bangalore,4.9,True,121000.0,1.0
8,109,Arjun Kapoor,HR,57000,26,2023-01-12,Mumbai,3.7,False,62700.0,1.0
7,108,Divya Patel,Finance,74000,31,2019-04-25,Ahmedabad,4.2,True,81400.0,1.0
4,105,Kunal Joshi,Finance,71000,30,2020-11-18,Pune,3.5,False,78100.0,2.0
9,110,Meera Reddy,Engineering,95000,37,2017-06-08,Bangalore,4.9,True,104500.0,1.0
17,118,Riya Chopra,Marketing,63000,30,2020-08-19,Hyderabad,3.7,False,69300.0,2.0
2,103,Rohan Verma,Engineering,92000,35,2018-01-10,Bangalore,4.7,True,101200.0,2.0
10,111,Siddharth Das,Data Science,105000,33,2020-02-20,Hyderabad,4.8,True,115500.0,2.0
3,104,Sneha Iyer,HR,54000,27,2022-05-30,Chennai,4.1,True,59400.0,2.0
6,107,Vikram Nair,Marketing,67000,34,2018-09-14,Delhi,3.9,True,73700.0,1.0

# Merge / Join DataFrames

In [19]:
df1=pd.DataFrame({
    'id':[1,2,3],
    'name':['Alice','Bob','Charlie'],
    'department':['Hr','IT','Finance'],
    'salary':[50000,60000,55000]
})

df2=pd.DataFrame({
    'id':[4,5,6],
    'name':['David','Eve','Frank'],
    'department':['IT','Finance','Hr'],
    'salary':[65000,58000,52000]
})

merged_df=pd.concat([df1,df2],ignore_index=True)

In [22]:
merged_df

   id     name department  salary
0   1    Alice         Hr   50000
1   2      Bob         IT   60000
2   3  Charlie    Finance   55000
3   4    David         IT   65000
4   5      Eve    Finance   58000
5   6    Frank         Hr   52000